### ISSUE TITLE
树莓派4初始化波特率为100000时，提示不支持的波特率（115200就正常），请教一下咋回事儿

### ISSUE THREAD

**Issue by ningjx** [flyfire-cn/flyfire.CustomSerialPort#1]
Unsupported baud rate (0; Invalid argument)
at RJCP.IO.Ports.Native.UnixNativeSerial.ThrowException()
   at RJCP.IO.Ports.Native.UnixNativeSerial.set_BaudRate(Int32 value)
   at RJCP.IO.Ports.SerialPortStream.set_BaudRate(Int32 value)
上rjcp那提issue去 :)

找到原因了，linux那个库里面波特率写死了 只有列举的才行 看来得重新编译了

**Comment by ningjx** [comment]
作者只支持标准的波特率了，这个只能放弃了，pytho确实强大，几行代码就把读串口数据搞定了，然后用socket发送到我的.net客户端，曲线救国了
